blank_issues_enabled: false
contact_links:
  - name: mlr3 Book
    url: https://mlr3book.mlr-org.com/
    about: Book about the mlr3 ecosystem

  - name: Creating a reprex
    url: https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html
    about: Tutorial for providing reproducible examples
