blank_issues_enabled: false
contact_links:
  - name: Book
    url: https://mlr3book.mlr-org.com/
    about: Book about the mlr3 ecosystem

  - name: Website
    url: https://mlr-org.com
    about: The central website of mlr-org

  - name: Mattermost
    url: https://lmmisld-lmu-stats-slds.srv.mwn.de/mlr_invite/
    about: Central mlr-org communication channel
